version: "3.8"
services:
  dev:
    build: .
    command: sleep infinity
    volumes:
      - /var/run/docker.sock:/var/run/docker-host.sock
      - ..:/workspace:cached
      - ~/.aws/credentials:/aws/credentials
      #- "${GOOGLE_APPLICATION_CREDENTIALS}:/gcloud/credentials.json"
    environment:
      AWS_SHARED_CREDENTIALS_FILE: /aws/credentials
      GOOGLE_APPLICATION_CREDENTIALS: /gcloud/credentials.json
    ports:
      - 3000:3000
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
